name: Terraform RDS

on:
  workflow_run:
    workflows: ["Terraform Validate"]
    types:
      - completed

jobs:
  rds:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=infra/rds init

      - name: Terraform Plan
        run: terraform -chdir=infra/rds plan -no-color

      - name: Terraform Apply
        run: terraform -chdir=infra/rds apply -auto-approve
